AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CD Demo Lambda
Resources:
  CDDemoLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda_function.lambda_handler
      Runtime: python3.7
      CodeUri: ./LambdaCode
      Description: 'Lambda function for CD Demo'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::974361912317:role/CloudFormationServiceRoleDemo02'
      Events:
        getAZsAPI:
          Type: Api
          Properties:
            Path: /getazs
            Method: get
      Environment:
        Variables:
          REGION: eu-west-2
      VpcConfig:
        SecurityGroupIds:
          - sg-0ef0598463ebe908b
        SubnetIds:
          - subnet-03a0c3ae56c6bdce6
          - subnet-088e3663d86d6ab33
